=== kerwanp/the-regex-game-levels/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://the-regex-game.com/level.schema.json",
  "title": "Level",
  "description": "A level for The Regex Game",
  "type": "object",
  "properties": {
    "name": {
      "description": "The name of the level",
      "type": "string"
    },
    "category": {
      "description": "The category of the level",
      "type": "string"
    },
    "difficulty": {
      "description": "The difficulty of the level from 1 to 5 (used to calculate scores)",
      "type": "integer"
    },
    "description": {
      "description": "The description of the level",
      "type": "string"
    },
    "tests": {
      "description": "The tests of the level",
      "type": "object",
      "properties": {
        "shouldMatch": {
          "description": "The tests that should match the Regex",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "value": {
                "description": "The value that should match the Regex",
                "type": "string"
              },
              "match": {
                "description": "The captured values that should match the Regex",
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": ["value", "match"]
          }
        },
        "shouldNotMatch": {
          "description": "The tests that should not match the Regex",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "value": {
                "description": "The value that should not match the Regex",
                "type": "string"
              }
            },
            "required": ["value"]
          }
        }
      }
    }
  },
  "required": ["name", "difficulty", "description", "tests"]
}

=== kerwanp/the-regex-game-levels/integer.json
{
  "$schema": "./schema.json",
  "name": "Simple Number",
  "difficulty": 1,
  "description": "Write a Regex that can match a positive or negative number.",
  "category": "Data",
  "tests": {
    "shouldMatch": [
      {
        "value": "1",
        "match": []
      },
      {
        "value": "0",
        "match": []
      },
      {
        "value": "50540",
        "match": []
      },
      {
        "value": "5980522015487",
        "match": []
      },
      {
        "value": "-10",
        "match": []
      },
      {
        "value": "-9874",
        "match": []
      }
    ],
    "shouldNotMatch": [
      {
        "value": "05"
      },
      {
        "value": "-0548"
      },
      {
        "value": "ab21"
      },
      {
        "value": "000"
      },
      {
        "value": "048-7004"
      },
      {
        "value": "0487004-"
      },
      {
        "value": "--0487004"
      }
    ]
  }
}

=== kerwanp/the-regex-game-levels/integer-captured.json
{
  "$schema": "./schema.json",
  "name": "Catpured Number",
  "difficulty": 3,
  "description": "Write a Regex that can capture a positive or negative number with leading zeros.",
  "category": "Data",
  "tests": {
    "shouldMatch": [
      {
        "value": "1",
        "match": ["1"]
      },
      {
        "value": "0",
        "match": ["0"]
      },
      {
        "value": "50540",
        "match": ["50540"]
      },
      {
        "value": "5980522015487",
        "match": ["5980522015487"]
      },
      {
        "value": "-10",
        "match": ["-10"]
      },
      {
        "value": "-9874",
        "match": ["-9874"]
      },
      {
        "value": "05",
        "match": ["5"]
      },
      {
        "value": "-0548",
        "match": ["-548"]
      },
      {
        "value": "000",
        "match": ["0"]
      }
    ],
    "shouldNotMatch": [
      {
        "value": "ab21"
      },
      {
        "value": "048-7004"
      },
      {
        "value": "0487004-"
      },
      {
        "value": "--0487004"
      }
    ]
  }
}

=== kerwanp/the-regex-game-levels/form-type-easy.json
{
  "$schema": "./schema.json",
  "name": "Form type - Easy",
  "description": "Form types is how <a href='https://www.sec.gov/forms'>the U.S. SECURITIES AND EXCHANGE COMMISSION</a> label company filing, often the first task of web scraping in natural language processing.",
  "difficulty": 2,
  "category": "Web",
  "tests": {
    "shouldMatch": [
      {
        "value": "1-A",
        "match": [
          "1-A"
        ]
      },
      {
        "value": "1-N",
        "match": [
          "1-N"
        ]
      },
      {
        "value": "11-K",
        "match": [
          "11-K"
        ]
      },
      {
        "value": "12b-25",
        "match": [
          "12b-25"
        ]
      },
      {
        "value": "19b-4(e)",
        "match": [
          "19b-4(e)"
        ]
      }
    ],
    "shouldNotMatch": [
      {
        "value": "ABS-15G"
      },
      {
        "value": "ABS D-15E"
      },
      {
        "value": "MA-NR"
      },
      {
        "value": "11MA-41K"
      },
      {
        "value": "LK3-EQ8"
      }
    ]
  }
}
