=== kerwanp/the-regex-game-levels/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://the-regex-game.com/level.schema.json",
  "title": "Level",
  "description": "A level for The Regex Game",
  "type": "object",
  "properties": {
    "name": {
      "description": "The name of the level",
      "type": "string"
    },
    "category": {
      "description": "The category of the level",
      "type": "string"
    },
    "difficulty": {
      "description": "The difficulty of the level from 1 to 5 (used to calculate scores)",
      "type": "integer"
    },
    "description": {
      "description": "The description of the level",
      "type": "string"
    },
    "tests": {
      "description": "The tests of the level",
      "type": "object",
      "properties": {
        "shouldMatch": {
          "description": "The tests that should match the Regex",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "value": {
                "description": "The value that should match the Regex",
                "type": "string"
              },
              "match": {
                "description": "The captured values that should match the Regex",
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": ["value", "match"]
          }
        },
        "shouldNotMatch": {
          "description": "The tests that should not match the Regex",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "value": {
                "description": "The value that should not match the Regex",
                "type": "string"
              }
            },
            "required": ["value"]
          }
        }
      }
    }
  },
  "required": ["name", "difficulty", "description", "tests"]
}

=== kerwanp/the-regex-game-levels/hostname.json
{
  "$schema": "./schema.json",
  "name": "Hostname",
  "difficulty": 1,
  "category": "Web",
  "description": "Write a Regex that can match a hostname. Without scheme nor path.",
  "tests": {
    "shouldMatch": [
      {
        "value": "the-regex-game.com",
        "match": []
      },
      {
        "value": "www.x.com",
        "match": []
      },
      {
        "value": "hello-5849.com",
        "match": []
      },
      {
        "value": "this.subdomain.com",
        "match": []
      },
      {
        "value": "again1.again2.subdomain.com",
        "match": []
      },
      {
        "value": "127.0.0.1",
        "match": []
      },
      {
        "value": "10.1.0.13:3000",
        "match": []
      },
      {
        "value": "localhost",
        "match": []
      },
      {
        "value": "localhost:69",
        "match": []
      },
      {
        "value": "martin-paucot.fr:4200",
        "match": []
      }
    ],
    "shouldNotMatch": [
      {
        "value": "world."
      },
      {
        "value": "the_regex_game.com"
      },
      {
        "value": ".not-a.hostname"
      },
      {
        "value": "www.x.co5"
      },
      {
        "value": "example.org:nop"
      }
    ]
  }
}

=== kerwanp/the-regex-game-levels/amqp-uri.json
{
  "$schema": "./schema.json",
  "name": "AMQP URI",
  "category": "Web",
  "difficulty": 3,
  "description": "Write a Regex that matches an AMQP URI and captures its parameters. You can find the specification on the official documentation <a href=\"https://www.rabbitmq.com/docs/uri-spec\" target=\"_blank\">https://www.rabbitmq.com/docs/uri-spec</a>",
  "tests": {
    "shouldMatch": [
      {
        "value": "amqp://user:password@mq.the-regex-game.com:5672/myvhost?option=1",
        "match": [
          "amqp",
          "user",
          "password",
          "mq.the-regex-game.com",
          "5672",
          "myvhost",
          "option=1"
        ]
      },
      {
        "value": "amqp://mq.the-regex-game.com/123",
        "match": ["amqp", "", "", "mq.the-regex-game.com", "", "123"]
      },
      {
        "value": "amqp://user@localhost:5672",
        "match": ["amqp", "user", "", "localhost", "5672"]
      },
      {
        "value": "amqp://user@localhost",
        "match": ["amqp", "user", "", "localhost"]
      },
      {
        "value": "amqp://default:default@127.0.0.1/hello?option1=1&option2=2",
        "match": [
          "amqp",
          "default",
          "default",
          "127.0.0.1",
          "",
          "hello",
          "option1=1&option2=2"
        ]
      }
    ],
    "shouldNotMatch": [
      {
        "value": "redis://user:password@mq.the-regex-game.com:5672/myvhost?option=1",
        "hint": "Should only allow 'amqp' scheme"
      },
      {
        "value": "redis://:password@localhost",
        "hint": "Should not only have a password"
      },
      {
        "value": "redis://user:password@localhost:nop",
        "hint": "Should not have letters in the port"
      },
      {
        "value": "redis://user:password@localhost:/vhost",
        "hint": "Should always have a port if there is ':'"
      }
    ]
  }
}

=== kerwanp/the-regex-game-levels/ipv4-noob.json
{
  "$schema": "./schema.json",
  "name": "IPV4",
  "description": "Write a Regex that matches an IP address. In this easy version, you do not have capture the segments nor care about the range.",
  "difficulty": 1,
  "category": "Web",
  "tests": {
    "shouldMatch": [
      {
        "value": "127.0.0.1",
        "match": []
      },
      {
        "value": "10.1.0.1",
        "match": []
      },
      {
        "value": "192.168.35.155",
        "match": []
      },
      {
        "value": "0.0.0.0",
        "match": []
      }
    ],
    "shouldNotMatch": [
      {
        "value": "192.168.155"
      },
      {
        "value": "192.35.155.12."
      },
      {
        "value": "1.1.155."
      },
      {
        "value": "1921.155.58.12"
      },
      {
        "value": "192.1551.878.12"
      },
      {
        "value": "192.155.5878.12"
      },
      {
        "value": "192.15.78.1211"
      },
      {
        "value": "192155587812"
      }
    ]
  }
}

=== kerwanp/the-regex-game-levels/ipv4-medium.json
{
  "$schema": "./schema.json",
  "name": "IPV4",
  "description": "Write a Regex that matches an IPV4 address. You must capture the segments and make sure that the range is correct.",
  "difficulty": 3,
  "category": "Web",
  "tests": {
    "shouldMatch": [
      {
        "value": "127.0.0.1",
        "match": ["127", "0", "0", "1"]
      },
      {
        "value": "10.1.0.1",
        "match": ["10", "1", "0", "1"]
      },
      {
        "value": "192.168.35.155",
        "match": ["192", "168", "35", "155"]
      },
      {
        "value": "0.0.0.0",
        "match": ["0", "0", "0", "0"]
      },
      {
        "value": "255.255.255.255",
        "match": ["255", "255", "255", "255"]
      }
    ],
    "shouldNotMatch": [
      {
        "value": "192.168.155"
      },
      {
        "value": "192.35.155.12."
      },
      {
        "value": "1.1.155."
      },
      {
        "value": "192.168.155.58.12"
      },
      {
        "value": "1921.155.58.12"
      },
      {
        "value": "192.155.5878.12"
      },
      {
        "value": "192155587812"
      },
      {
        "value": "350.2.10.8"
      },
      {
        "value": "89.648.11.15"
      },
      {
        "value": "89.158.256.125"
      }
    ]
  }
}

=== kerwanp/the-regex-game-levels/ipv4-easy.json
{
  "$schema": "./schema.json",
  "name": "IPV4 - Easy",
  "description": "Internet Protocol version 4 (IPv4) is the fourth version of the Internet Protocol (IP). It is one of the core protocols of standards-based internetworking methods in the Internet and other packet-switched networks.",
  "difficulty": 2,
  "category": "Web",
  "tests": {
    "shouldMatch": [
      {
        "value": "127.0.0.1",
        "match": []
      },
      {
        "value": "10.1.0.1",
        "match": []
      },
      {
        "value": "192.168.35.155",
        "match": []
      },
      {
        "value": "0.0.0.0",
        "match": []
      }
    ],
    "shouldNotMatch": [
      {
        "value": "192.168.155"
      },
      {
        "value": "192.35.155.12."
      },
      {
        "value": "1.1.155."
      },
      {
        "value": "1921.155.58.12"
      },
      {
        "value": "192.1551.878.12"
      },
      {
        "value": "192.155.5878.12"
      },
      {
        "value": "192.15.78.1211"
      },
      {
        "value": "192155587812"
      }
    ]
  }
}

=== kerwanp/the-regex-game-levels/float.json
{
  "$schema": "./schema.json",
  "name": "Float",
  "difficulty": 3,
  "category": "Data",
  "description": "Write a Regex that can match negative and positive float numbers.",
  "tests": {
    "shouldMatch": [
      {
        "value": "1.5",
        "match": []
      },
      {
        "value": "187.54548",
        "match": []
      },
      {
        "value": "187.54548",
        "match": []
      },
      {
        "value": ".420",
        "match": []
      },
      {
        "value": "30035.",
        "match": []
      },
      {
        "value": "-69.45",
        "match": []
      }
    ],
    "shouldNotMatch": [
      {
        "value": "554"
      },
      {
        "value": "-0548"
      },
      {
        "value": "ab21"
      },
      {
        "value": "54..8"
      },
      {
        "value": "80.54.48"
      },
      {
        "value": "048-7004"
      },
      {
        "value": "0487004-"
      },
      {
        "value": "--0487004."
      },
      {
        "value": "."
      }
    ]
  }
}

=== kerwanp/the-regex-game-levels/form-type-medium.json
{
  "$schema": "./schema.json",
  "name": "Form type - Medium",
  "description": "Form types is how <a href='https://www.sec.gov/forms'>the U.S. SECURITIES AND EXCHANGE COMMISSION</a> label company filing, often the first task of web scraping in natural language processing.",
  "difficulty": 4,
  "category": "Web",
  "tests": {
    "shouldMatch": [
      {
        "value": "ABS-15G",
        "match": [
          "ABS-15G"
        ]
      },
      {
        "value": "X-17A-5",
        "match": [
          "X-17A-5"
        ]
      },
      {
        "value": "24F-2",
        "match": [
          "24F-2"
        ]
      },
      {
        "value": "CFPORTAL",
        "match": [
          "CFPORTAL"
        ]
      },
      {
        "value": "N-17f-2",
        "match": [
          "N-17f-2"
        ]
      }
    ],
    "shouldNotMatch": [
      {
        "value": "ABS-GGEF"
      },
      {
        "value": "ABS D-15E"
      },
      {
        "value": "LKA0f0-F"
      },
      {
        "value": "IJG1-JKA"
      },
      {
        "value": "JEQB1-PB2"
      }
    ]
  }
}

=== kerwanp/the-regex-game-levels/searchparams.json
{
  "$schema": "./schema.json",
  "name": "Search params",
  "description": "Write a Regex that matches and capture encoded URL Search Params.",
  "category": "Web",
  "difficulty": 4,
  "tests": {
    "shouldMatch": [
      {
        "value": "hello=world",
        "match": ["hello", "world"]
      },
      {
        "value": "1=one",
        "match": ["1", "one"]
      },
      {
        "value": "one=1&2=two",
        "match": ["one", "1", "2", "two"]
      },
      {
        "value": "o_k=o_k&o-k=o-k&OK=OK&o.k=o.k",
        "match": ["o_k", "o_k", "o-k", "o-k", "OK", "OK", "o.k", "o.k"]
      },
      {
        "value": "json=%7B%22hello%22%3A%22world%3F%22%7D",
        "match": ["json", "%7B%22hello%22%3A%22world%3F%22%7D"]
      },
      {
        "value": "empty=",
        "match": ["empty", ""]
      },
      {
        "value": "empty1=&empty2=",
        "match": ["empty1", "", "empty2", ""]
      },
      {
        "value": "=ytpme",
        "match": ["", "ytpme"]
      }
    ],
    "shouldNotMatch": [
      {
        "value": "not=ok"
      },
      {
        "value": "the=regex?game"
      },
      {
        "value": "the=ga\"me"
      },
      {
        "value": "shoud=not=match"
      },
      {
        "value": "the=game&=hey"
      },
      {
        "value": "alone"
      },
      {
        "value": "nop=test]"
      }
    ]
  }
}
